spring:
  servlet:
      multipart:
        max-file-size: 25MB      # 파일 하나의 최대 크기
        max-request-size: 25MB   # 요청 전체 최대 크기 (form-data 합계)
  datasource:
    url: "jdbc:mysql://localhost:3306/pium?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8"
    username: root
    password: "1105"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false